matrix:
  include:
  - language: android
    android:
      components:
      - build-tools-27.0.1
      - android-24
      - extra
      - addon
      - sys-img-armeabi-v7a-android-24
    before_install:
    - mkdir /home/travis/screenshots/
    - export DATE=`date`
    - export CURRENT_FOLDER="release $DATE"
    - mkdir /home/travis/$CURRENT_FOLDER
    - export PATH=$PATH:$JAVA_HOME/bin
    - export ANDROID_HOME=/usr/local/android-sdk/
    - nvm install 8
    before_script:
    - npm install -g appium
    - npm install -g appium-doctor
    - appium-doctor
    - echo no | android create avd --force -n testEmu2 -t android-24 --abi armeabi-v7a
    - emulator -avd testEmu2 -no-skin -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - appium &
    script:
    - mvn clean test
    - ls screenshots/ -a
    - cp -r screenshots/ /home/travis/$CURRENT_FOLDER
    - date
notifications:
  email:
  - gabriel@cbqasolutions.com
deploy:
  provider: s3
  access_key_id: AKIAJ6D7R2ZC4K37ZHXQ
  secret_access_key:
    secure: ce1jXMB/VPnmnpyE635AeJHW1rF8uU8UfERuJxPSFbli3lHrtOYRFjR6arvZP+nbrilCzT24wiPXA6RoEDk2GEzkUbUIvjlNk+4M69YIDeDVA7CR+kb02rTqfRUC55StsueVyQweglKzkUrKJeZwg2wST0uq/vfzGf+bcudQA1ddwHERKDcje9V3F4LQZhj3OBaLDfcPRh8ut36wjpyhZjPLnFcJg/wcGWIAi3IKu5FvbaSzwyGtBC4z2tecpBfeBsjw3SbqyWCo1UkWlXHfivtIrtXDAt6c/5RiHPYgYxAyqEa9HEapK9vDos48DTCZ3MrnX1R/mEzeJeLJ+ejf6BAUSFL99UMyheNvkyi4ksW4va+mtGT+zndoteph3Z6IWwkuRSAWq4zLGCDCvcG2A3DSNz+uXIUoIfCnCRzRKJjSGKAqCCgv3VYeJ1wKSK1XhsJ0JchPH9Q98/4e108+70Sf4n87pJ9kVW37wI5WJ/2B14DL0cRGxjMbtRJP3ZQ3ojTRz3lkeGL4wgphztYlj0zW0uOSo9eKOYth7LoCE2QCp15DlbN/oIMtGsCLbj8x5XchyBmeuGLpKxtQPXngdFdP1u6a1EJIE9wsrWXS/Zypjs7xeiLdw6V/8JVTany8RTyfZox4Z0u+KCkcpeg0JXjf3Z6UVVUgcIw9FS5od+8=
  bucket: travis-demo
  acl: public_read
  skip_cleanup: true
  on:
    repo: gabriel-cbqa/app-automation-test
