matrix:
  include:
  - language: android
    android:
      components:
        - build-tools-22.0.1
        - android-22
        - extra
        - addon
        - sys-img-armeabi-v7a-android-22
    before_install:
      - mkdir /home/travis/screenshots/
      - export PATH=$PATH:$JAVA_HOME/bin
      - export ANDROID_HOME=/usr/local/android-sdk/
      - nvm install 6
    before_script:
      - npm install -g appium
      - npm install -g appium-doctor
      - appium-doctor
      - echo no | android create avd --force -n testEmu2 -t android-22 --abi armeabi-v7a
      - emulator -avd testEmu2 -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      - appium &
    script:
      - mvn clean test
      - ls /home/travis/screenshots/ -a
      - cp target/surefire-reports/emailable-report.html /home/travis/screenshots/
      - zip /home/travis/screenshots/
    before_deploy:
      - gem install travis
      - travis encrypt KEY="cb4f40eee4d81ccff41361badab2f447e58ec2e8"
    deploy:
      provider: releases
      api_key:
        secure: KEY
      file: /home/travis/screenshots.zip
      skip_cleanup: true
      on:
        tags: true
notifications:
  email:
    - gabriel@cbqasolutions.com
