language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
    - addon
    - sys-img-armeabi-v7a-android-22
before_script: 
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - brew install node
  - npm install -g appium
  - appium
  - echo no | android create avd --force -n testEmu2 -t android-22 --abi armeabi-v7a
  - emulator -avd testEmu2 -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb devices
  
script: 
  - mvn clean test
