matrix:
  include:
  - language: android
    android:
      components:
        - build-tools-22.0.1
        - android-22
        - extra
        - addon
        - sys-img-armeabi-v7a-android-22
    before_install:
      - export PATH=$PATH:$JAVA_HOME/bin
      - export ANDROID_HOME=/usr/local/android-sdk/
      - nvm install 6
    before_script:
      - npm install -g appium
      - npm install -g appium-doctor
      - appium-doctor
      - echo no | android create avd --force -n testEmu2 -t android-22 --abi armeabi-v7a
      - emulator -avd testEmu2 -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      - appium &
    script:
      - mvn clean test
      - ls ~/screenshots/ -a
notifications:
  email:
    - gabriel@cbqasolutions.com

